'use client';
import { useState } from 'react';
import { track } from '@vercel/analytics';
const amazon='https://www.amazon.com/dp/B0HKDYG29Z';
const chapters=['Welcome to Norway. Good luck.','Why does nobody speak like my textbook?','School survival','How to make a Norwegian friend','Norwegian Teenager™','The Norwegian texting department','The Norwegian word “koselig”','Ja. Nei. Jo. Jaja. Neida. Joda.','Things Norwegians say that don’t mean what you think','Please don’t say that','Emergency Norwegian','The 100 phrases that will save you'];
const phrases=[
 ['I DON’T UNDERSTAND · #1','Hæ?','Huh? / What?','The classic.'],
 ['BASIC HUMAN FUNCTIONING · #20','Det går bra.','It’s okay / I’m fine / No problem.','The Swiss Army knife of Norwegian sentences.'],
 ['MAKING FRIENDS · #35','Kan jeg bli med?','Can I come along / join?','One of the most important sentences in this book.'],
 ['CONVERSATION SAVERS · #43','Kødder du?','Are you joking / Are you kidding me?','Useful information. Use responsibly.'],
 ['CONVERSATION SAVERS · #49','Kanskje.','Maybe.','Potentially yes. Potentially no. Good luck.'],
 ['TEXTING & SOCIAL LIFE · #54','Jeg er på vei.','I’m on my way.','Are you? Interesting.'],
 ['TEXTING & SOCIAL LIFE · #56','Jeg blir litt sen.','I’m going to be a little late.','Define litt at your own risk.'],
 ['EXTREMELY NORWEGIAN NORWEGIAN · #94','Takk for sist!','Thanks for last time.','Still weird. Still Norwegian.'],
 ['EXTREMELY NORWEGIAN NORWEGIAN · #95','Jo!','Yes, actually!','When contradicting something negative. You’ve defeated the boss.'],
 ['EXTREMELY NORWEGIAN NORWEGIAN · #98','Jaja.','Yeah yeah / okay / oh well / anyway / fine.','Emotion unavailable in your region.'],
 ['EXTREMELY NORWEGIAN NORWEGIAN · #99','Det ordner seg.','It’ll work out.','An excellent Norwegian philosophy.']
];
function Buy({where='hero',children='GET HÆ?! ON AMAZON →'}){return <a className="cta" href={amazon} target="_blank" rel="noreferrer" onClick={()=>track('amazon_click',{location:where})}>{children}</a>}
export default function Page(){const [i,setI]=useState(0); const next=()=>{setI((i+1)%phrases.length);track('phrase_generator_click',{phrase:phrases[(i+1)%phrases.length][1]})};return <main>
<section className="hero wrap"><div className="heroCopy"><div className="kicker">NORWEGIAN FOR REAL LIFE</div><h1>You learned Norwegian.<br/><em>Then Norwegians started talking.</em></h1><p className="lede">The Norwegian Survival Guide Nobody Gave You.</p><p>For anyone who knows the words — but still occasionally has absolutely no idea what Norwegians are talking about.</p><Buy/><small>Kindle edition · Available on Amazon</small></div><div className="heroBook"><img src="/book-mockup.png" alt="HÆ?! Norwegian for Real Life book"/></div></section>
<section className="problem"><div className="wrap"><div className="eyebrow">THE PROBLEM</div><h2>Your textbook wasn’t wrong.<br/><span>It just left some things out.</span></h2><div className="moments"><article><b>kanskje?</b><p>“Maybe” isn’t always maybe.</p></article><article><b>jo.</b><p>Good luck finding a clean English equivalent.</p></article><article><b>“sometime”</b><p>Sounds like a plan. Might just be politeness.</p></article><article><b>HÆ?!</b><p>Tone, context and tiny words can change everything.</p></article></div></div></section>
<section className="manifesto wrap"><div className="eyebrow">THE WHOLE POINT</div><h2>You don’t need perfect Norwegian.<br/><span>You need useful Norwegian.</span></h2><p>The kind that helps when everyone else seems to know what’s happening. The kind that helps you talk to someone your own age. The kind that helps when the bus driver says something and you have absolutely no idea what it was.</p><strong>That’s where HÆ?! starts.</strong></section>
<section className="toc"><div className="wrap"><div className="eyebrow">12 CHAPTERS · REAL NORWEGIAN · MINIMAL DIGNITY</div><h2>What’s actually inside?</h2><div className="chapterList">{chapters.map((c,n)=><div className="chapter" key={c}><span>{String(n+1).padStart(2,'0')}</span><h3>{c}</h3></div>)}</div></div></section>
<section className="hundred wrap"><div className="hundredNum">100</div><div className="hundredCopy"><div className="eyebrow">CHAPTER 12</div><h2>100 phrases that will save you.</h2><p>You don’t need to memorise them all today. Steal the useful ones. Use them. Make them yours.</p><div className="phrase"><small>{phrases[i][0]}</small><h3>{phrases[i][1]}</h3><b>{phrases[i][2]}</b><p>{phrases[i][3]}</p><button onClick={next}>GIVE ME ANOTHER →</button></div><p className="more">That’s a few. The book has 100.</p><Buy where="phrases">GET THE OTHER ONES →</Buy></div></section>
<section className="notbook"><div className="wrap"><div className="eyebrow">SO WHAT KIND OF BOOK IS THIS?</div><h2>Not really a grammar book.<br/>Not really a phrasebook.<br/><span>More like the missing manual for actually being in Norway.</span></h2><p>Language is only part of understanding Norwegians. The rest lives in tone, humour, social codes, indirectness, texting, friendship, school, everyday expressions — and all the things people assume you already know.</p></div></section>
<section className="author wrap"><img src="/nanny.jpg" alt="Nanny Thorvaldsen"/><div><div className="eyebrow">THE PERSON RESPONSIBLE</div><h2>Hi, I’m Nanny.</h2><p>I’m a Norwegian teacher, writer and former marketing and content strategist fascinated by culture, communication and the strange little rules people somehow know without ever being taught.</p><p>Before moving into education, I worked across marketing, social media and content, including several years with Spotify in Norway. Today I teach Norwegian to newly arrived teenagers from around the world.</p><p><strong>HÆ?! grew out of the questions that appeared when textbook Norwegian met actual Norway.</strong></p></div></section>
<section className="final"><div className="wrap finalGrid"><div><div className="eyebrow">YOU MADE IT THIS FAR.</div><h2>Know the words.<br/><span>Understand the Norwegians.</span></h2><p>HÆ?! — Norwegian for Real Life</p><Buy where="footer"/><small>Jaja. Det ordner seg.</small></div><img src="/book-cover.jpg" alt="HÆ?! book cover"/></div></section>
</main>}
